name: Export de métricas

on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'NOT RELEASE') == false
    runs-on: "ubuntu-latest"
    environment: actions
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install dotenv
        run: pip install python-dotenv
          
      - name: Cria arquivo .env
        run: |
          touch ./sonar_scripts/.env
          echo TOKEN=${{ secrets.API_TOKEN_GITHUB }} >> ./scripts/.env
          echo RELEASE_MAJOR=${{ contains(github.event.pull_request.labels.*.name, 'MAJOR RELEASE') }} >> ./scripts/.env
          echo RELEASE_MINOR=${{ contains(github.event.pull_request.labels.*.name, 'MINOR RELEASE') }} >> ./scripts/.env
          echo RELEASE_FIX=${{ contains(github.event.pull_request.labels.*.name, 'FIX RELEASE') }} >> ./scripts/.env
          echo DEVELOP=${{ contains(github.event.pull_request.labels.*.name, 'DEVELOP') }} >> ./scripts/.env

      - name: Criar diretório
        run: mkdir analytics-raw-data

      - name: Coletar métricas no SonarCloud
        run: python ./sonar_scripts/parser.py

      - name: Envia métricas para repo de Doc
        run: |
          git config --global user.email "${{secrets.USER_EMAIL}}"
          git config --global user.name "${{secrets.USER_NAME}}"
          git clone --single-branch --branch main "https://x-access-token:${{secrets.API_TOKEN_DOC}}@github.com/fga-eps-mds/2024.1-UnB-TV-DOC" doc
          mkdir -p doc/analytics-raw-data
          cp -R analytics-raw-data/*.json doc/analytics-raw-data
          cd doc
          git add .
          git commit -m "Adicionando métricas do repositório ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push
